### ISSUE TITLE
Good API permissions but unable to open trades

### ISSUE THREAD

**Issue by domagojhack** [sann05/python-currencycom#2]
All reading commands work great but when trying to open new trades I get an error. My API key has the permission to trade.

After 

`client.new_order("DOGE/USD", OrderSide.SELL, OrderType.MARKET, 19, None, 1 )`

I am getting this response:

{'code': -1025, 'msg': 'Invalid API-key, IP, or permissions for action'}

**Comment by sann05** [comment]
Hello @DomagojHack,

It doesn't seem like an issue with the library.

The same behavior appeared while trading BTC/USD, ETH/USD etc. 

I send a request to Currency.com support. I'll keep you posted

**Comment by domagojhack** [comment]
Any news?

**Comment by sann05** [comment]
```
Customer Support (Currency.com)

May 8, 2021, 17:50 GMT+3

Dear Aleksandr,

Thank you for providing us with the information promptly.

They have been forwarded to the respective department. We will do our best to provide you with a reply as soon as possible. Please, keep in mind that in some cases it could take up to 2-3 business days.

Thank you for your patience and kind cooperation.
Best regards,

Customer support department
Currency Com Bel LLC
```

**Comment by domagojhack** [comment]
bump

**Comment by sann05** [comment]
I follow the situation. No responses from the support

**Comment by sann05** [comment]
Hello @DomagojHack,

I found an issue with the lib and updated it.

As for now, it works fine for version python-currencycom==0.2.2

Example:
```
client.new_order(
    symbol="DOGE/USD",
    side=OrderSide.BUY,
    order_type=OrderType.LIMIT,
    new_order_resp_type=NewOrderResponseType.RESULT,
    quantity=1,
    price=0.3
)
```

Response:
```
{'symbol': 'DOGE/USD', 'orderId': '00000000-0000-0000-0000-00000340c028', 'transactTime': 1621416404769, 'price': '0.30000000', 'origQty': '1', 'executedQty': '0.0', 'status': 'NEW', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'BUY'}
```

**Comment by domagojhack** [comment]
Thanks for the update. Gonna try it out when possible.
