### ISSUE TITLE
client.close_trading_position(neworder[-1]['orderId'],None);

### ISSUE THREAD

**Issue by a-nai** [sann05/python-currencycom#6]
{'code': -1128, 'msg': 'Position not found'}

How to get position id if it changed with 'orderId'

**Comment by sann05** [comment]
I'm not sure what you're asking. Could you please provide exact piece of code you're trying to execute

**Comment by a-nai** [comment]
client.close_trading_position(client.list_leverage_trades(None)["positions"][-1]['id'],None)
