### ISSUE TITLE
{'code': -1021, 'msg': "Your time (1641393721429) doesn't match server time (1641393733341)"}

### ISSUE THREAD

**Issue by a-nai** [sann05/python-currencycom#7]
neworder.append(client.new_order('BTC/USD_LEVERAGE',OrderSide.SELL,OrderType.MARKET,(client.get_account_info()["balances"][0]['free']*0.95*10)/bi()[0],client.get_account_info()["balances"][0]['accountId'],None,False,None,None,10,None,NewOrderResponseType.FULL,None));

{'code': -1021, 'msg': "Your time (1641393721429) doesn't match server time (1641393733341)"}

**Comment by sann05** [comment]
This is a wrapper for currency.com API.
Your questions related to issues with API, so could you please start with looking through API documentation:
https://currency.com/ru/api
